### ISSUE TITLE
How to set when have two objects?

### ISSUE THREAD

**Issue by jinjunfei** [marinbenc/medical-polar-training#3]
How should this be solved when there are two disconnected segmentation targets in the image, and the center point (centroid) of the mask is set to a position in the middle? (As shown)
![Figure_1](https://user-images.githubusercontent.com/58759199/160236306-f6f20829-afa6-4fe9-82c0-963cb8f05235.png)

**Comment by marinbenc** [comment]
Hello,

The polar transformation might not be the best usecase for this example, but there are a few things you can try. One way to deal with this would be to use the largest connected component to get the centroid. We have tried this and did not see a large difference in our examples, but it might work better for you. Take a look at the `lcc` parameter here:

https://github.com/marinbenc/medical-polar-training/blob/91f9540a07dc63138faa23c36031236d4e616b8c/polar_transformations.py#L7

There might be more clever solutions with cropping all images and similar.
