### ISSUE TITLE
Valid Data for liver

### ISSUE THREAD

**Issue by FatimaGH5** [marinbenc/medical-polar-training#7]
Where can I find valid data of liver ? 
On the website I found just the train and test https://competitions.codalab.org/competitions/17094#participate

**Comment by marinbenc** [comment]
Hi Fatima,

I'm sorry for the late response. We make our own validation data split in the following script:

https://github.com/marinbenc/medical-polar-training/blob/main/datasets/liver/scans_to_images.py

You need to place the downloaded scans in the directory as described in the README, but there's no need for a valid folder.
